### 🛍️ Get All Products
GET http://localhost:3000/api/products
Content-Type: application/json

### 🛍️ Get All Products Paginated
GET http://localhost:3000/api/products/paginated/all?limit=2
Content-Type: application/json

### 🛍️ Get All Products Paginated, next page
GET http://localhost:3000/api/products/paginated/all?limit=2&page_info=eyJsYXN0X2lkIjo3ODcxOTkxNjc2OTUxLCJsYXN0X3ZhbHVlIjoiY29sZCBkZXciLCJkaXJlY3Rpb24iOiJuZXh0In0
Content-Type: application/json

### 🛍️ Get All Contacts
GET http://localhost:3000/api/contacts
Content-Type: application/json

###

### ➕ Create a Product
POST http://localhost:3000/api/products
Content-Type: application/json

{
  "title": "New Product from REST Client",
  "body_html": "<strong>Awesome product</strong>",
  "vendor": "Demo Vendor",
  "product_type": "Custom",
  "variants": [{ "price": "29.99" }]
}

###

### 👤 Create a Customer
POST http://localhost:3000/api/contacts
Content-Type: application/json

{
  "first_name": "Jane",
  "last_name": "Doe",
  "email": "jane.doe@example.com"
}

###

### 📦 Get All Orders
GET http://localhost:3000/api/orders
Content-Type: application/json
